@startuml

class WorkspaceConfiguration {
  - userRuntimeRecipe
  - plugins
}

class ChePlugin {
  - name
  - version
  - endpoints
  - containers
}

WorkspaceConfiguration *-- ChePlugin

note as pluginnote
 - language servers
 - terminal
 - git plugin
 etc...
end note

pluginnote .. ChePlugin

@enduml